name: Build Alokai dev

on:
  push:
    branches: [ develop ]

jobs:
  deployment:
    runs-on: [self-hosted, development]
    steps:
    - run: |
        echo "-------- Deploying https://alokai-dev.labs.erpgap.com/ "
        /home/egap/.local/bin/deploy-vsf-1
