name: Build Alokai prod

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: [self-hosted, production]
    steps:
    - run: |
        echo "-------- Deploying https://alokai.labs.erpgap.com/ "
        /home/egap/.local/bin/deploy-vsf-1
